CursoMvcBruna/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using CursoMvcBruna.ViewModels;
using CursoMvcBruna.Repository;
using CursoMvcBruna.Models;
using CursoMvcBruna.CrossCuttingMvcFilters;

namespace CursoMvcBruna.Controllers
{
    [GlobalErrorHandler]
    public class ClientesController : Controller
    {
        private readonly IClienteRepository _clienteRepository;

        public ClientesController(IClienteRepository clienteRepository)
        {

            _clienteRepository = clienteRepository;
        }


        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            var Clientes = _clienteRepository.ObterTodos();
            return View(Clientes);
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Cliente = _clienteRepository.ObterPorId(id);

            if (Cliente == null)
            {
                return NotFound();
            }

            return View(Cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClienteEnderecoViewModel clienteEnderecoViewModel)
        {
            if (ModelState.IsValid)
            {
                Cliente cliente = new Cliente()
                {
                    Nome = clienteEnderecoViewModel.Nome,
                    Email = clienteEnderecoViewModel.Email,
                    CPF = clienteEnderecoViewModel.CPF,
                    DataNascimento = clienteEnderecoViewModel.DataNascimento,
                    DataCadastro = DateTime.Now,
                    Ativo = true
                };

                Endereco endereco = new Endereco()
                {
                    Logradouro = clienteEnderecoViewModel.Logradouro,
                    Numero = clienteEnderecoViewModel.Numero,
                    Complemento = clienteEnderecoViewModel.Complemento,
                    Bairro = clienteEnderecoViewModel.Bairro,
                    CEP = clienteEnderecoViewModel.CEP,
                    Cidade = clienteEnderecoViewModel.Cidade,
                    Estado = clienteEnderecoViewModel.Estado
                };

                cliente.Enderecos.Add(endereco);

                _clienteRepository.Adicionar(cliente);
                return RedirectToAction(nameof(Index));
            }
            return View(clienteEnderecoViewModel);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = _clienteRepository.ObterPorId(id);
            if (cliente == null)
            {
                return NotFound();
            }

            ClienteViewModel clienteViewModel = new ClienteViewModel()
            {
                Nome = cliente.Nome,
                Email = cliente.Email,
                CPF = cliente.CPF,
                DataNascimento = cliente.DataNascimento,
                DataCadastro = DateTime.Now,
                Ativo = true
            };

            return View(clienteViewModel);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(ClienteViewModel clienteViewModel)
        {
           
            var cliente = _clienteRepository.ObterPorCPF(clienteViewModel.CPF);


            if (cliente == null)
            {
                return NotFound();
            }
                
                        
            cliente.Nome = clienteViewModel.Nome;
            cliente.Email = clienteViewModel.Email;
            cliente.CPF = clienteViewModel.CPF;
            cliente.DataNascimento = clienteViewModel.DataNascimento;
                
            

            _clienteRepository.Atualizar(cliente);

            return RedirectToAction(nameof(Index));
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = _clienteRepository.ObterPorId(id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_clienteRepository == null)
            {
                return Problem("Entity set 'CursoMvcContext.ClienteViewModel'  is null.");
            }
            var cliente = _clienteRepository.ObterPorId(id);
            if (cliente != null)
            {
                _clienteRepository.Remover(id);
            }


            return RedirectToAction(nameof(Index));
        }
  }
}

CursoMvcBruna/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CursoMvcBruna</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/bootswatchTheme.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CursoMvcBruna.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/a4fcdde7a0.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bruna Application</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            <span class="visually-hidden">(current)</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                       @* <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>*@
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2023 - Projeto Bruna - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
   @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>